## MID TERM

In [88]:

import os 
import pandas as pd

import numpy as np
from lets_plot import *
LetsPlot.setup_html()

In [89]:
all_files = [os.path.join('D:/me204/data/waitrose', file) for file in os.listdir('D:/me204/data/waitrose') 
             if file.endswith('.csv')]
all_files

['D:/me204/data/waitrose\\baby-child-and-parent.csv',
 'D:/me204/data/waitrose\\bakery.csv',
 'D:/me204/data/waitrose\\beer-wine-and-spirits.csv',
 'D:/me204/data/waitrose\\best-of-british.csv',
 'D:/me204/data/waitrose\\dietary-and-lifestyle.csv',
 'D:/me204/data/waitrose\\everyday-value.csv',
 'D:/me204/data/waitrose\\food-cupboard.csv',
 'D:/me204/data/waitrose\\fresh-and-chilled.csv',
 'D:/me204/data/waitrose\\frozen.csv',
 'D:/me204/data/waitrose\\home.csv',
 'D:/me204/data/waitrose\\household.csv',
 'D:/me204/data/waitrose\\new.csv',
 'D:/me204/data/waitrose\\organic-shop.csv',
 'D:/me204/data/waitrose\\pet.csv',
 'D:/me204/data/waitrose\\summer.csv',
 'D:/me204/data/waitrose\\tea-coffee-and-soft-drinks.csv',
 'D:/me204/data/waitrose\\toiletries-health-and-beauty.csv',
 'D:/me204/data/waitrose\\waitrose-brands.csv']

In [90]:
df = pd.concat((pd.read_csv(file) for file in all_files))

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25418 entries, 0 to 1593
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   data-product-id        25418 non-null  int64
 1   data-product-name      25418 non-null  object
 2   data-product-type      25418 non-null  object
 3   data-product-on-offer  25418 non-null  bool
 4   data-product-index     25408 non-null  float64
 5   image-url              25418 non-null  object
 6   product-page           25418 non-null  object
 7   product-name           25407 non-null  object
 8   product-size           25363 non-null  object
 9   item-price             25407 non-null  object
 10  price-per-unit         24976 non-null  object
 11  offer-description      7201 non-null   object
 12  category               25418 non-null  object
dtypes: bool(1), float64(1), int64(1), object(10)
memory usage: 2.5+ MB

In [92]:
df = df.drop_duplicates()

df = df.drop(columns=['data-product-name', 
                      'data-product-type', 
                      'data-product-index'])
df = (
    df.rename(columns={
        'data-product-id': 'id',
        'data-product-on-offer': 'offer',
        'product-page': 'page',
        "offer-description":"offer_description",
        'product-name': 'name',
        'product-size': 'size',
        'item-price':'price',
    })
)

In [93]:
df=df.drop(columns = ['image-url','page'])

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25378 entries, 0 to 1593
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 25378 non-null  int64
 1   offer              25378 non-null  bool
 2   name               25367 non-null  object
 3   size               25323 non-null  object
 4   price              25367 non-null  object
 5   price-per-unit     24936 non-null  object
 6   offer_description  7178 non-null   object
 7   category           25378 non-null  object
dtypes: bool(1), int64(1), object(6)
memory usage: 1.6+ MB

## TASK 01 – DATA CLEANING:

## Reduce the Data Frame so that each row represents a unique product

In [95]:
df["offer_description"]=df["offer_description"].fillna("Not on offer")

In [96]:
df

,id,offer,name,size,price,price-per-unit,offer_description,category
0,525635,False,Organix Raspberry & Apple Soft Oaty Bars,6x23g,£3.15,£2.29/100g,Not on offer,"Baby, Child & Parent"
1,557746,False,Organix Carrot Cake Oaty Bars,6x23g,£3.15,£2.29/100g,Not on offer,"Baby, Child & Parent"
2,32062,False,Aptamil 2 Follow On Milk,800g,£13.50,£16.88/kg,Not on offer,"Baby, Child & Parent"
3,767801,False,Essential Baby Wipes,80s,95p,1.2p each,Not on offer,"Baby, Child & Parent"
4,514054,False,Organix Apple Rice Cakes,40g,£1.60,£4/100g,Not on offer,"Baby, Child & Parent"
...,...,...,...,...,...,...,...,...
1589,18427,False,Duchy Organic British Lamb Half Leg,Typical weight 0.94kg,£24.31 each est.,£26.00/kg,Not on offer,Waitrose Brands
1590,11606,False,Cooks' Ingredients Wok Oil,250ml,£2.40,96p/100ml,Not on offer,Waitrose Brands
1591,6903,False,No. 1 Badoz Vacherin Du Haut-Doubs AOP French ...,350g,£10.00,£28.58/kg,Not on offer,Waitrose Brands
1592,6125,False,Cooks' Ingredients White Marzipan,500g,£2.50,£5/kg,Not on offer,Waitrose Brands
1593,707668,False,Duchy Organic Pinot Grigio Bag in Box,2.25L,£21.49,£7.17/75cl,Not on offer,Waitrose Brands

In [97]:
df['category'] =df.groupby('name')['category'].transform(lambda x: ', '.join(x.unique()))

In [98]:
df.drop_duplicates(inplace=True)

In [99]:
df

,id,offer,name,size,price,price-per-unit,offer_description,category
0,525635,False,Organix Raspberry & Apple Soft Oaty Bars,6x23g,£3.15,£2.29/100g,Not on offer,"Baby, Child & Parent"
1,557746,False,Organix Carrot Cake Oaty Bars,6x23g,£3.15,£2.29/100g,Not on offer,"Baby, Child & Parent"
2,32062,False,Aptamil 2 Follow On Milk,800g,£13.50,£16.88/kg,Not on offer,"Baby, Child & Parent, Toiletries, Health & Beauty"
3,767801,False,Essential Baby Wipes,80s,95p,1.2p each,Not on offer,"Baby, Child & Parent, Summer, Toiletries, Heal..."
4,514054,False,Organix Apple Rice Cakes,40g,£1.60,£4/100g,Not on offer,"Baby, Child & Parent, Dietary & Lifestyle"
...,...,...,...,...,...,...,...,...
35,85201,False,Essential Leeks,Typical weight 0.21kg,57p each est.,£2.75/kg,Not on offer,Waitrose Brands
1098,461285,False,Cooks' Ingredients Chargrilled Peppers in Oil,drained 170g,£3.50,£2.06/100g,Not on offer,Waitrose Brands
1293,539814,True,Cooks' Ingredients Frozen Herby Chimichurri Po...,350g,£1.75,50p/100g,Reduced to Clear. Was £3.50,Waitrose Brands
1330,589503,False,Cooks' Ingredients Artichokes in Oil,drained 160g,£3.50,£2.19/100g,Not on offer,Waitrose Brands
1438,723407,False,Cooks' Ingredients Frozen Stir Fry Vegetable Mix,400g,£2.00,50p/100g,Not on offer,Waitrose Brands

In [100]:
categories = df.groupby('name')['category'].apply(list).reset_index()
categories.rename(columns={"category": "categories"}, inplace=True)

# Merge the new column into the original DataFrame
df = df.merge(categories, on="name")

In [101]:
df

,id,offer,name,size,price,price-per-unit,offer_description,category,categories
0,525635,False,Organix Raspberry & Apple Soft Oaty Bars,6x23g,£3.15,£2.29/100g,Not on offer,"Baby, Child & Parent","[Baby, Child & Parent]"
1,557746,False,Organix Carrot Cake Oaty Bars,6x23g,£3.15,£2.29/100g,Not on offer,"Baby, Child & Parent","[Baby, Child & Parent]"
2,32062,False,Aptamil 2 Follow On Milk,800g,£13.50,£16.88/kg,Not on offer,"Baby, Child & Parent, Toiletries, Health & Beauty","[Baby, Child & Parent, Toiletries, Health & Be..."
3,767801,False,Essential Baby Wipes,80s,95p,1.2p each,Not on offer,"Baby, Child & Parent, Summer, Toiletries, Heal...","[Baby, Child & Parent, Summer, Toiletries, Hea..."
4,514054,False,Organix Apple Rice Cakes,40g,£1.60,£4/100g,Not on offer,"Baby, Child & Parent, Dietary & Lifestyle","[Baby, Child & Parent, Dietary & Lifestyle, Ba..."
...,...,...,...,...,...,...,...,...,...
16049,85201,False,Essential Leeks,Typical weight 0.21kg,57p each est.,£2.75/kg,Not on offer,Waitrose Brands,[Waitrose Brands]
16050,461285,False,Cooks' Ingredients Chargrilled Peppers in Oil,drained 170g,£3.50,£2.06/100g,Not on offer,Waitrose Brands,[Waitrose Brands]
16051,539814,True,Cooks' Ingredients Frozen Herby Chimichurri Po...,350g,£1.75,50p/100g,Reduced to Clear. Was £3.50,Waitrose Brands,[Waitrose Brands]
16052,589503,False,Cooks' Ingredients Artichokes in Oil,drained 160g,£3.50,£2.19/100g,Not on offer,Waitrose Brands,[Waitrose Brands]
16053,723407,False,Cooks' Ingredients Frozen Stir Fry Vegetable Mix,400g,£2.00,50p/100g,Not on offer,Waitrose Brands,[Waitrose Brands]

In [102]:
categories= df.groupby('name').agg(
    categories=('category', lambda x: list(x.unique())),  
   ).reset_index()

In [103]:
df = df.drop(columns=['category'])
df

,id,offer,name,size,price,price-per-unit,offer_description,categories
0,525635,False,Organix Raspberry & Apple Soft Oaty Bars,6x23g,£3.15,£2.29/100g,Not on offer,"[Baby, Child & Parent]"
1,557746,False,Organix Carrot Cake Oaty Bars,6x23g,£3.15,£2.29/100g,Not on offer,"[Baby, Child & Parent]"
2,32062,False,Aptamil 2 Follow On Milk,800g,£13.50,£16.88/kg,Not on offer,"[Baby, Child & Parent, Toiletries, Health & Be..."
3,767801,False,Essential Baby Wipes,80s,95p,1.2p each,Not on offer,"[Baby, Child & Parent, Summer, Toiletries, Hea..."
4,514054,False,Organix Apple Rice Cakes,40g,£1.60,£4/100g,Not on offer,"[Baby, Child & Parent, Dietary & Lifestyle, Ba..."
...,...,...,...,...,...,...,...,...
16049,85201,False,Essential Leeks,Typical weight 0.21kg,57p each est.,£2.75/kg,Not on offer,[Waitrose Brands]
16050,461285,False,Cooks' Ingredients Chargrilled Peppers in Oil,drained 170g,£3.50,£2.06/100g,Not on offer,[Waitrose Brands]
16051,539814,True,Cooks' Ingredients Frozen Herby Chimichurri Po...,350g,£1.75,50p/100g,Reduced to Clear. Was £3.50,[Waitrose Brands]
16052,589503,False,Cooks' Ingredients Artichokes in Oil,drained 160g,£3.50,£2.19/100g,Not on offer,[Waitrose Brands]
16053,723407,False,Cooks' Ingredients Frozen Stir Fry Vegetable Mix,400g,£2.00,50p/100g,Not on offer,[Waitrose Brands]

In [104]:
df.dropna()

,id,offer,name,size,price,price-per-unit,offer_description,categories
0,525635,False,Organix Raspberry & Apple Soft Oaty Bars,6x23g,£3.15,£2.29/100g,Not on offer,"[Baby, Child & Parent]"
1,557746,False,Organix Carrot Cake Oaty Bars,6x23g,£3.15,£2.29/100g,Not on offer,"[Baby, Child & Parent]"
2,32062,False,Aptamil 2 Follow On Milk,800g,£13.50,£16.88/kg,Not on offer,"[Baby, Child & Parent, Toiletries, Health & Be..."
3,767801,False,Essential Baby Wipes,80s,95p,1.2p each,Not on offer,"[Baby, Child & Parent, Summer, Toiletries, Hea..."
4,514054,False,Organix Apple Rice Cakes,40g,£1.60,£4/100g,Not on offer,"[Baby, Child & Parent, Dietary & Lifestyle, Ba..."
...,...,...,...,...,...,...,...,...
16049,85201,False,Essential Leeks,Typical weight 0.21kg,57p each est.,£2.75/kg,Not on offer,[Waitrose Brands]
16050,461285,False,Cooks' Ingredients Chargrilled Peppers in Oil,drained 170g,£3.50,£2.06/100g,Not on offer,[Waitrose Brands]
16051,539814,True,Cooks' Ingredients Frozen Herby Chimichurri Po...,350g,£1.75,50p/100g,Reduced to Clear. Was £3.50,[Waitrose Brands]
16052,589503,False,Cooks' Ingredients Artichokes in Oil,drained 160g,£3.50,£2.19/100g,Not on offer,[Waitrose Brands]
16053,723407,False,Cooks' Ingredients Frozen Stir Fry Vegetable Mix,400g,£2.00,50p/100g,Not on offer,[Waitrose Brands]

## Keep a item-price column with the original price of the item.

In [105]:
def clean_item_price(price: str):  

    if ' each est.'in price:
        price = price.replace(' each est.','') 
    if type(price)!=str:
        pass
    elif '£' in price:
        price = price.replace('£', '')
    elif 'p' in price:
        price = price.replace('p', '')
        price = '0.' + price

    if '-' in price:
       price = price.split('-')[0]

     
    return float(price)
df['price-fixed']=df['price'].astype(str).apply(clean_item_price)

In [106]:
selected_rows = df['price'].astype(str).str.contains('-')

df.loc[selected_rows,'size'] = df.loc[selected_rows,'size'].str.split('-').str[0].str.replace('(','')

In [107]:
df['price']=df['price-fixed']
df.drop(columns=['price-fixed'],inplace=True)

In [108]:
df

,id,offer,name,size,price,price-per-unit,offer_description,categories
0,525635,False,Organix Raspberry & Apple Soft Oaty Bars,6x23g,3.15,£2.29/100g,Not on offer,"[Baby, Child & Parent]"
1,557746,False,Organix Carrot Cake Oaty Bars,6x23g,3.15,£2.29/100g,Not on offer,"[Baby, Child & Parent]"
2,32062,False,Aptamil 2 Follow On Milk,800g,13.50,£16.88/kg,Not on offer,"[Baby, Child & Parent, Toiletries, Health & Be..."
3,767801,False,Essential Baby Wipes,80s,0.95,1.2p each,Not on offer,"[Baby, Child & Parent, Summer, Toiletries, Hea..."
4,514054,False,Organix Apple Rice Cakes,40g,1.60,£4/100g,Not on offer,"[Baby, Child & Parent, Dietary & Lifestyle, Ba..."
...,...,...,...,...,...,...,...,...
16049,85201,False,Essential Leeks,Typical weight 0.21kg,0.57,£2.75/kg,Not on offer,[Waitrose Brands]
16050,461285,False,Cooks' Ingredients Chargrilled Peppers in Oil,drained 170g,3.50,£2.06/100g,Not on offer,[Waitrose Brands]
16051,539814,True,Cooks' Ingredients Frozen Herby Chimichurri Po...,350g,1.75,50p/100g,Reduced to Clear. Was £3.50,[Waitrose Brands]
16052,589503,False,Cooks' Ingredients Artichokes in Oil,drained 160g,3.50,£2.19/100g,Not on offer,[Waitrose Brands]
16053,723407,False,Cooks' Ingredients Frozen Stir Fry Vegetable Mix,400g,2.00,50p/100g,Not on offer,[Waitrose Brands]

In [109]:
df_cleaned = (
    df.groupby("id", as_index=False)
    .agg({
        "categories": lambda x: list(x)  # Collect all categories in a list
}))
df_cleaned

           id                                         categories
0        1023                      [[Tea, Coffee & Soft Drinks]]
1        1029                                  [[Food Cupboard]]
2        1048             [[Dietary & Lifestyle, Food Cupboard]]
3        1051             [[Dietary & Lifestyle, Food Cupboard]]
4        1052  [[Dietary & Lifestyle, Food Cupboard, Dietary ...
...       ...                                                ...
16049  998674  [[New, Tea, Coffee & Soft Drinks, New, Tea, Co...
16050  999031                           [[Fresh & Chilled, New]]
16051  999167                             [[Food Cupboard, New]]
16052  999432                                 [[Household, New]]
16053  999942                                      [[Home, New]]

[16054 rows x 2 columns]

## specific Product ##

In [110]:
bananas= df[
    df['name'].str.contains('Bananas', case=False, na=False) & 
     (df['categories'].str.contains('everyday', case=False, na=False) | 
    ~df['categories'].str.contains('everyday', case=False, na=False))
]

In [111]:
with pd.option_context('display.max_rows', None,):
    print(bananas)

          id  offer                                               name  \
34    508625  False                   Ella's Kitchen Peaches & Bananas
36    756513  False        Ella's Kitchen Blueberries Apples + Bananas
40     79877  False                    Ella's Kitchen Bananas & Apples
50    621160  False                  Ella's Kitchen Bananas & Coconuts
140   773625   True                       Ella's Kitchen Puree Bananas
2913   88903  False                        Essential Fairtrade Bananas
2915   88528  False                        Essential Fairtrade Bananas
2928   33668  False                   Waitrose Small Fairtrade Bananas
2956   88937  False                    Duchy Organic Fairtrade Bananas
4536  446346   True  Innocent Strawberries & Bananas Fruit Smoothie...
4550   25050   True     Innocent Strawberries & Bananas Fruit Smoothie
4781  537221   True  Innocent Pineapples, Bananas & Coconuts Fruit ...

                       size  price price-per-unit  \
34                     120g   1.35     £1.13/100g
36                     120g   1.35     £1.13/100g
40                     120g   1.35     £1.13/100g
50                     120g   1.35     £1.13/100g
140                     70g   1.00     £1.43/100g
2913  Typical weight 0.18kg   0.20       £1.10/kg
2915                     5s   0.95       19p each
2928                     7s   1.25     17.9p each
2956                     6s   1.95     32.5p each
4536                  750ml   2.50    33.3p/100ml
4550                  250ml   2.10      84p/100ml
4781                  750ml   2.50    £3.34/litre

                                      offer_description  \
34                                         Not on offer
36                                         Not on offer
40                                         Not on offer
50                                         Not on offer
140                                     Add 5 for £4.50
2913                                       Not on offer
2915                                       Not on offer
2928                                       Not on offer
2956                                       Not on offer
4536                              save £1.20. Was £3.70
4550  £5 Food to Go Meal Deal: Add 1 Main, 1 Snack a...
4781                              save £1.20. Was £3.70

                                             categories
34                 [Baby, Child & Parent, Organic Shop]
36                               [Baby, Child & Parent]
40    [Baby, Child & Parent, Dietary & Lifestyle, Or...
50                               [Baby, Child & Parent]
140                              [Baby, Child & Parent]
2913  [Dietary & Lifestyle, Everyday Value, Fresh & ...
2915  [Dietary & Lifestyle, Everyday Value, Fresh & ...
2928             [Dietary & Lifestyle, Fresh & Chilled]
2956  [Dietary & Lifestyle, Fresh & Chilled, Organic...
4536  [Dietary & Lifestyle, Fresh & Chilled, Tea, Co...
4550  [Dietary & Lifestyle, Fresh & Chilled, Tea, Co...
4781  [Dietary & Lifestyle, Fresh & Chilled, Tea, Co...

In [112]:
bananas_remove=["Ella's Kitchen Peaches & Bananas","Ella's Kitchen Puree Bananas","Ella's Kitchen Blueberries Apples", "Ella's Kitchen Bananas & Apples", "Ella's Kitchen Bananas & Coconuts", "Innocent Strawberries & Bananas Fruit Smoothie", "Innocent Strawberries & Bananas Fruit Smoothie", "Ella's Kitchen Bananas & Apples", "Innocent Pineapples, Bananas & Coconuts Fruit Smoothie","Innocent Strawberries & Bananas Fruit Smoothie", "Innocent Strawberries & Bananas Fruit Smoothie", "Innocent Pineapples, Bananas & Coconuts Fruit Smoothie", "Ella's Kitchen Peaches & Bananas", "Ella's Kitchen Bananas & Apples", "Innocent Strawberries & Bananas Fruit Smoothie", "Innocent Strawberries & Bananas Fruit Smoothie", "Innocent Pineapples, Bananas & Coconuts Fruit Smoothie"]
bananas= bananas[~bananas['name'].str.contains('|'.join(bananas_remove), case=False, na=False)]
bananas

,id,offer,name,size,price,price-per-unit,offer_description,categories
2913,88903,False,Essential Fairtrade Bananas,Typical weight 0.18kg,0.20,£1.10/kg,Not on offer,"[Dietary & Lifestyle, Everyday Value, Fresh & ..."
2915,88528,False,Essential Fairtrade Bananas,5s,0.95,19p each,Not on offer,"[Dietary & Lifestyle, Everyday Value, Fresh & ..."
2928,33668,False,Waitrose Small Fairtrade Bananas,7s,1.25,17.9p each,Not on offer,"[Dietary & Lifestyle, Fresh & Chilled]"
2956,88937,False,Duchy Organic Fairtrade Bananas,6s,1.95,32.5p each,Not on offer,"[Dietary & Lifestyle, Fresh & Chilled, Organic..."

In [113]:
bananas_plot = bananas[['id','name','size','price','categories']]
bananas_plot=bananas_plot.sort_values('price')
bananas_plot

,id,name,size,price,categories
2913,88903,Essential Fairtrade Bananas,Typical weight 0.18kg,0.20,"[Dietary & Lifestyle, Everyday Value, Fresh & ..."
2915,88528,Essential Fairtrade Bananas,5s,0.95,"[Dietary & Lifestyle, Everyday Value, Fresh & ..."
2928,33668,Waitrose Small Fairtrade Bananas,7s,1.25,"[Dietary & Lifestyle, Fresh & Chilled]"
2956,88937,Duchy Organic Fairtrade Bananas,6s,1.95,"[Dietary & Lifestyle, Fresh & Chilled, Organic..."

In [114]:
(
    ggplot(bananas_plot, aes(x='name', y='price')) +
    geom_line(color='red', size=1.2) +
    labs(
        title='Price of Bananas',
        x='Product Name',
        y='Price ($)'
    ) +  
    theme(
        axis_text_x=element_text(hjust=1),  
        plot_title=element_text(size=14, face='bold')  
    ) + ggsize(600, 800)+
        theme_grey() +\
        flavor_high_contrast_dark()      
)

In [138]:
tooltip_setup=(layer_tooltips()
               .line("@name")
               .line("[@price]") 
               .line("[@size]")
               .format("@price", "$ {.2f}")
)


(
    ggplot(bananas_plot,aes(y="name",x="price",fill="name"))+
    geom_linerange(size=1, alpha=.7, tooltips=tooltip_setup)+
    geom_point(size=3, stroke=1, shape=21, tooltips=tooltip_setup)+
    scale_fill_discrete(guide="none")+
    scale_y_continuous(name="name\n(from largest to smallest median)",expand=[.05,.05])+
    labs(title="'fresh fruit'has the highest median price for individual items",
         subtitle="bananas")+
    theme(axis_text_x=element_text(size=11),
          axis_text_y=element_text(size=11),
          axis_title_x=element_text(size=15),
          axis_title_y=element_text(size=15),
          plot_title=element_text(size=19, face="bold"),
          plot_subtitle=element_text(size=14),
          legend_position="none")+
    ggsize(1000,500)
)